ALTER TABLE orders
DROP CONSTRAINT orders_address_id_fkey,
    DROP COLUMN address_id,
    ADD COLUMN full_name CHARACTER VARYING(255),
    ADD COLUMN phone_number CHARACTER VARYING(20),
    ADD COLUMN email CHARACTER VARYING(255),
    ADD COLUMN street CHARACTER VARYING(255),
    ADD COLUMN address_line2 CHARACTER VARYING(255),
    ADD COLUMN city CHARACTER VARYING(255),
    ADD COLUMN ghn_province_id INTEGER,
    ADD COLUMN ghn_district_id INTEGER,
    ADD COLUMN ghn_ward_code CHARACTER VARYING(16),
    ADD COLUMN province_name CHARACTER VARYING(255),
    ADD COLUMN district_name CHARACTER VARYING(255),
    ADD COLUMN ward_name CHARACTER VARYING(255);

