payos_link_expiry: 300 # in seconds
minimum_day_before_contract_payment_due: 5 # in days
representative_name: "Đinh Thị Ngọc Trinh"
representative_role: "Beauty Blogger"
representative_phone: "+84917956697"
representative_email: "mrstrinh.work@gmail.com"
representative_tax_number: "01234567890"
representative_bank_name: "Ngân hàng TMCP Quân đội"
representative_bank_account_number: "3730 0944 4882 74"
representative_bank_account_holder: "TRAN GIANH KHANH"
